//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wb_follower")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub follower_id: i32,
    pub followee_id: i32,
    pub status: i16,
    pub created_time: i32,
    pub updated_time: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
