//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wb_user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub uid: i32,
    pub phone: String,
    pub password: String,
    pub created_time: Option<i32>,
    pub updated_time: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
