//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "wb_user_info")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub uid: i32,
    pub nickname: Option<String>,
    pub avatar: Option<String>,
    pub gender: Option<i16>,
    pub birthday: Option<i32>,
    pub updated_time: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
